### ISSUE TITLE
 关于文件夹的项目

### ISSUE THREAD

**Issue by darkr4y** [rootphantomer/hack_tools_for_me#1]
都是国人就不用英文了。
这些项目在Git上本身就存在，不需要额外添加目录过来，可以使用[submodule](http://git-scm.com/book/zh/Git-%E5%B7%A5%E5%85%B7-%E5%AD%90%E6%A8%A1%E5%9D%97)来直接添加这类项目的引用。

**Comment by rootphantomer** [comment]
嗯，有道理，后续有时间整理下。
